import { Amplify } from 'aws-amplify';
import outputs from '../../../amplify_outputs.json';

/**
 * Configure Amplify with generated outputs
 * 
 * The amplify_outputs.json file is generated by 'npx ampx sandbox' or 'npx ampx deploy'
 * It contains all the configuration for Auth, API, Storage, etc.
 */
export function configureAmplify(): void {
  Amplify.configure(outputs);
  
  // Enable verbose logging in development
  if (import.meta.env.DEV) {
    // Amplify.Logger.LOG_LEVEL = 'DEBUG';
  }
}

/**
 * Re-export Amplify for convenience
 */
export { Amplify };
